name: Generate ReaPack index

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate index.xml
        uses: cfillion/reapack-index@v1
        with:
          output: index.xml

      - name: Commit index
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add index.xml
          git commit -m "Update index.xml" || echo "No changes"
          git push
